-- Your SQL goes here
CREATE TABLE CUSTOMER(
    ID INTEGER(8) NOT NULL PRIMARY KEY,
    DOCUMENT VARCHAR(50) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    SECOND_NAME VARCHAR(255),
    PERSON_TYPE CHAR(1) NOT NULL,
    DEVICE_ID VARCHAR(36)
);
